version: '3'
services:
  harmony:
    build: .
    image: harmony
    ports:
      - "8080:8080"
    volumes:
      - ./ethash:/root/ethereumj/ethash
    networks:
      - ethereum

networks:
  ethereum:
    driver: bridge